### ISSUE TITLE
Currently incompatible with Android libraries

### ISSUE THREAD

**Issue by chris-hatton** [irgaly/compose-vector-plugin#17]
このプラグインは、Compose Multiplatform の冒険で SVG を楽しく活用するのにピッタリです！ただ、一つだけ問題があります！

現時点では、Android ライブラリプロジェクトと互換性がありません。詳しくは、以下の ComposeVectorPlugin.kt の抜粋をご覧ください 👇 

---

This plugin looks perfect for making joyful  use of SVG in Compose Multiplatform adventures - There is only one problem!

Its's currently incompatible with Android Library projects, see:

Excerpt from `ComposeVectorPlugin.kt`
```
    /**
     * Run Block in finalizeDsl when Android Plugin available
     * or in afterEvaluate when Android Plugin not available.
     */
    private fun Project.executeOnFinalize(block: () -> Unit) {
        var hasAndroid = false
        listOf("com.android.application", "com.android.library").forEach { pluginId ->
            pluginManager.withPlugin(pluginId) {
                hasAndroid = true
                extensions.configure<ApplicationAndroidComponentsExtension> {
                    finalizeDsl {
                        block()
                    }
                }
            }
        }
        afterEvaluate {
            if (!hasAndroid) {
                block()
            }
        }
    }
```

このコードは、ライブラリプロジェクトでは存在しないはずの ApplicationAndroidComponentsExtension 型の拡張を解決しようとしています。先ほど com.android.library プラグインを参照しているので、これは単純なバグだと思われます。

---

...this code tries to resolve an extension of type `ApplicationAndroidComponentsExtension` which by definition won't be present in a Library project. Given that you are looking for `com.android.library` plugin types above; I imagine this is simply a bug.

**Comment by irgaly** [comment]
Thank you for your detailed report!

I merged your PR #18 , and release new version [v1.0.0](https://github.com/irgaly/compose-vector-plugin/releases/tag/v1.0.0). Please use new one and enjoy Kotlin & Compose! 😄

**Comment by chris-hatton** [comment]
Thanks!
